name: Docs

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  BuildTheDocs:
    name: BuildTheDocs
    runs-on: ubuntu-latest

    steps:

      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Run BuildTheDocs and publish to GitHub Pages'
        uses: buildthedocs/btd@v0
        with:
          token: ${{ github.token }}

      - name: 'Upload artifacts'
        uses: actions/upload-artifact@master
        with:
          name: doc
          path: docs/_build/html
